project:
  type: website
  output-dir: docs

website:
  title: "Morgan Holland"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About
      - href: Teaching.qmd
        text: Teaching
      - href: research.qmd
        text: Academic Research
      - href: applied_research.qmd
        text: Applied Research and Consulting
      - href: CV.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog

format:
  html:
    theme: 
      - styles.scss
    
    toc: true

editor: visual

execute:
  freeze: true

